In [2]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("nikhilmittal/flight-fare-prediction-mh")

# print("Path to dataset files:", path)

In [3]:
import numpy as np,pandas as pd,matplotlib.pyplot as plt,seaborn as sns,warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_excel('../datasets/Data_Train.xlsx')
df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662

In [5]:
for i in df.columns:
    if (df[i].dtype=='O'):
        df[i]=df[i].str.strip()

In [6]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [7]:
df.replace('',np.nan,inplace=True)
df.replace('NaN',np.nan,inplace=True)

In [8]:
df.shape

(10683, 11)

In [9]:
df.dropna(axis=0,inplace=True)

In [10]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [11]:
df.shape

(10682, 11)

In [12]:
for i in df.columns:
    if (df[i].dtype=='O'):
        print(i)
        print(df[i].unique())
        print()

Airline
['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']

Date_of_Journey
['24/03/2019' '1/05/2019' '9/06/2019' '12/05/2019' '01/03/2019'
 '24/06/2019' '12/03/2019' '27/05/2019' '1/06/2019' '18/04/2019'
 '9/05/2019' '24/04/2019' '3/03/2019' '15/04/2019' '12/06/2019'
 '6/03/2019' '21/03/2019' '3/04/2019' '6/05/2019' '15/05/2019'
 '18/06/2019' '15/06/2019' '6/04/2019' '18/05/2019' '27/06/2019'
 '21/05/2019' '06/03/2019' '3/06/2019' '15/03/2019' '3/05/2019'
 '9/03/2019' '6/06/2019' '24/05/2019' '09/03/2019' '1/04/2019'
 '21/04/2019' '21/06/2019' '27/03/2019' '18/03/2019' '12/04/2019'
 '9/04/2019' '1/03/2019' '03/03/2019' '27/04/2019']

Source
['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']

Destination
['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']

Route
['BLR → DEL' 'CCU → IXR → BBI → BLR' 'DEL → LKO → BOM → COK'
 'CCU → NAG → BLR' 'BLR → NAG → DEL' 'CCU → BLR' 'BLR → BOM → DEL'
 'DEL → BOM → COK' 'DEL → BLR → COK' 'MAA → CCU' 'CCU → BOM → BLR'
 'DEL → AMD → BOM → COK' 'DEL → PNQ → COK' 'DEL → CCU → BOM → COK'
 'BLR → COK → DEL' 'DEL → IDR → BOM → COK' 'DEL → LKO → COK'
 'CCU → GAU → DEL → BLR' 'DEL → NAG → BOM → COK' 'CCU → MAA → BLR'
 'DEL → HYD → COK' 'CCU → HYD → BLR' 'DEL → COK' 'CCU → DEL → BLR'
 'BLR → BOM → AMD → DEL' 'BOM → DEL → HYD' 'DEL → MAA → COK' 'BOM → HYD'
 'DEL → BHO → BOM → COK' 'DEL → JAI → BOM → COK' 'DEL → ATQ → BOM → COK'
 'DEL → JDH → BOM → COK' 'CCU → BBI → BOM → BLR' 'BLR → MAA → DEL'
 'DEL → GOI → BOM → COK' 'DEL → BDQ → BOM → COK' 'CCU → JAI → BOM → BLR'
 'CCU → BBI → BLR' 'BLR → HYD → DEL' 'DEL → TRV → COK'
 'CCU → IXR → DEL → BLR' 'DEL → IXU → BOM → COK' 'CCU → IXB → BLR'
 'BLR → BOM → JDH → DEL' 'DEL → UDR → BOM → COK' 'DEL → HYD → MAA → COK'
 'CCU → BOM → COK → BLR' 'BLR → CCU → DEL' 'CCU → BOM → GOI → BLR'
 'DEL → RPR → NAG → BOM → COK' 'DEL → HYD → BOM → COK'
 'CCU → DEL → AMD → BLR' 'CCU → PNQ → BLR' 'BLR → CCU → GAU → DEL'
 'CCU → DEL → COK → BLR' 'BLR → PNQ → DEL' 'BOM → JDH → DEL → HYD'
 'BLR → BOM → BHO → DEL' 'DEL → AMD → COK' 'BLR → LKO → DEL'
 'CCU → GAU → BLR' 'BOM → GOI → HYD' 'CCU → BOM → AMD → BLR'
 'CCU → BBI → IXR → DEL → BLR' 'DEL → DED → BOM → COK'
 'DEL → MAA → BOM → COK' 'BLR → AMD → DEL' 'BLR → VGA → DEL'
 'CCU → JAI → DEL → BLR' 'CCU → AMD → BLR' 'CCU → VNS → DEL → BLR'
 'BLR → BOM → IDR → DEL' 'BLR → BBI → DEL' 'BLR → GOI → DEL'
 'BOM → AMD → ISK → HYD' 'BOM → DED → DEL → HYD' 'DEL → IXC → BOM → COK'
 'CCU → PAT → BLR' 'BLR → CCU → BBI → DEL' 'CCU → BBI → HYD → BLR'
 'BLR → BOM → NAG → DEL' 'BLR → CCU → BBI → HYD → DEL' 'BLR → GAU → DEL'
 'BOM → BHO → DEL → HYD' 'BOM → JLR → HYD' 'BLR → HYD → VGA → DEL'
 'CCU → KNU → BLR' 'CCU → BOM → PNQ → BLR' 'DEL → BBI → COK'
 'BLR → VGA → HYD → DEL' 'BOM → JDH → JAI → DEL → HYD'
 'DEL → GWL → IDR → BOM → COK' 'CCU → RPR → HYD → BLR' 'CCU → VTZ → BLR'
 'CCU → DEL → VGA → BLR' 'BLR → BOM → IDR → GWL → DEL'
 'CCU → DEL → COK → TRV → BLR' 'BOM → COK → MAA → HYD' 'BOM → NDC → HYD'
 'BLR → BDQ → DEL' 'CCU → BOM → TRV → BLR' 'CCU → BOM → HBX → BLR'
 'BOM → BDQ → DEL → HYD' 'BOM → CCU → HYD' 'BLR → TRV → COK → DEL'
 'BLR → IDR → DEL' 'CCU → IXZ → MAA → BLR' 'CCU → GAU → IMF → DEL → BLR'
 'BOM → GOI → PNQ → HYD' 'BOM → BLR → CCU → BBI → HYD' 'BOM → MAA → HYD'
 'BLR → BOM → UDR → DEL' 'BOM → UDR → DEL → HYD' 'BLR → VGA → VTZ → DEL'
 'BLR → HBX → BOM → BHO → DEL' 'CCU → IXA → BLR' 'BOM → RPR → VTZ → HYD'
 'BLR → HBX → BOM → AMD → DEL' 'BOM → IDR → DEL → HYD' 'BOM → BLR → HYD'
 'BLR → STV → DEL' 'CCU → IXB → DEL → BLR' 'BOM → JAI → DEL → HYD'
 'BOM → VNS → DEL → HYD' 'BLR → HBX → BOM → NAG → DEL'
 'BLR → BOM → IXC → DEL' 'BLR → CCU → BBI → HYD → VGA → DEL'
 'BOM → BBI → HYD']

Dep_Time
['22:20' '05:50' '09:25' '18:05' '16:50' '09:00' '18:55' '08:00' '08:55'
 '11:25' '09:45' '20:20' '11:40' '21:10' '17:15' '16:40' '08:45' '14:00'
 '20:15' '16:00' '14:10' '22:00' '04:00' '21:25' '21:50' '07:00' '07:05'
 '09:50' '14:35' '10:35' '15:05' '14:15' '06:45' '20:55' '11:10' '05:45'
 '19:00' '23:05' '11:00' '09:35' '21:15' '23:55' '19:45' '08:50' '15:40'
 '06:05' '15:00' '13:55' '05:55' '13:20' '05:05' '06:25' '17:30' '08:20'
 '19:55' '06:30' '14:05' '02:00' '09:40' '08:25' '20:25' '13:15' '02:15'
 '16:55' '20:45' '05:15' '19:50' '20:00' '06:10' '19:30' '04:45' '12:55'
 '18:15' '17:20' '15:25' '23:00' '12:00' '14:45' '11:50' '11:30' '14:40'
 '19:10' '06:00' '23:30' '07:35' '13:05' '12:30' '15:10' '12:50' '18:25'
 '16:30' '00:40' '06:50' '13:00' '19:15' '01:30' '17:00' '10:00' '19:35'
 '15:30' '12:10' '16:10' '20:35' '22:25' '21:05' '05:35' '05:10' '06:40'
 '15:15' '00:30' '08:30' '07:10' '05:30' '14:25' '05:25' '10:20' '17:45'
 '13:10' '22:10' '04:55' '17:50' '21:20' '06:20' '15:55' '20:30' '17:25'
 '09:30' '07:30' '02:35' '10:55' '17:10' '09:10' '18:45' '15:20' '22:50'
 '14:55' '14:20' '13:25' '22:15' '11:05' '16:15' '20:10' '06:55' '19:05'
 '07:55' '07:45' '10:10' '08:15' '11:35' '21:00' '17:55' '16:45' '18:20'
 '03:50' '08:35' '19:20' '20:05' '17:40' '04:40' '17:35' '09:55' '05:00'
 '18:00' '02:55' '20:40' '22:55' '22:40' '21:30' '08:10' '17:05' '07:25'
 '15:45' '09:15' '15:50' '11:45' '22:05' '18:35' '00:25' '19:40' '20:50'
 '22:45' '10:30' '23:25' '11:55' '10:45' '11:15' '12:20' '14:30' '07:15'
 '01:35' '18:40' '09:20' '21:55' '13:50' '01:40' '00:20' '04:15' '13:45'
 '18:30' '06:15' '02:05' '12:15' '13:30' '06:35' '10:05' '08:40' '03:05'
 '21:35' '16:35' '02:30' '16:25' '05:40' '15:35' '13:40' '07:20' '04:50'
 '12:45' '10:25' '12:05' '11:20' '21:40' '03:00']

Arrival_Time
['01:10 22 Mar' '13:15' '04:25 10 Jun' ... '06:50 10 Mar' '00:05 19 Mar'
 '21:20 13 Mar']

Duration
['2h 50m' '7h 25m' '19h' '5h 25m' '4h 45m' '2h 25m' '15h 30m' '21h 5m'
 '25h 30m' '7h 50m' '13h 15m' '2h 35m' '2h 15m' '12h 10m' '26h 35m'
 '4h 30m' '22h 35m' '23h' '20h 35m' '5h 10m' '15h 20m' '2h 55m' '13h 20m'
 '15h 10m' '5h 45m' '5h 55m' '13h 25m' '22h' '5h 30m' '10h 25m' '5h 15m'
 '2h 30m' '6h 15m' '11h 55m' '11h 5m' '8h 30m' '22h 5m' '2h 45m' '12h'
 '16h 5m' '19h 55m' '3h 15m' '25h 20m' '3h' '16h 15m' '15h 5m' '6h 30m'
 '25h 5m' '12h 25m' '27h 20m' '10h 15m' '10h 30m' '1h 30m' '1h 25m'
 '26h 30m' '7h 20m' '13h 30m' '5h' '19h 5m' '14h 50m' '2h 40m' '22h 10m'
 '9h 35m' '10h' '21h 20m' '18h 45m' '12h 20m' '18h' '9h 15m' '17h 30m'
 '16h 35m' '12h 15m' '7h 30m' '24h' '8h 55m' '7h 10m' '14h 30m' '30h 20m'
 '15h' '12h 45m' '10h 10m' '15h 25m' '14h 5m' '20h 15m' '23h 10m'
 '18h 10m' '16h' '2h 20m' '8h' '16h 55m' '3h 10m' '14h' '23h 50m'
 '21h 40m' '21h 15m' '10h 50m' '8h 15m' '8h 35m' '11h 50m' '27h 35m'
 '8h 25m' '20h 55m' '4h 50m' '8h 10m' '24h 25m' '23h 35m' '25h 45m'
 '26h 10m' '28h 50m' '25h 15m' '9h 20m' '9h 10m' '3h 5m' '11h 30m'
 '9h 30m' '17h 35m' '5h 5m' '25h 50m' '20h' '13h' '18h 25m' '24h 10m'
 '4h 55m' '25h 35m' '6h 20m' '18h 40m' '19h 25m' '29h 20m' '9h 5m'
 '10h 45m' '11h 40m' '22h 55m' '37h 25m' '25h 40m' '13h 55m' '8h 40m'
 '23h 30m' '12h 35m' '24h 15m' '1h 20m' '11h' '11h 15m' '14h 35m'
 '12h 55m' '9h' '7h 40m' '11h 45m' '24h 55m' '17h 5m' '29h 55m' '22h 15m'
 '14h 40m' '7h 15m' '20h 10m' '20h 45m' '27h' '24h 30m' '20h 25m' '5h 35m'
 '14h 45m' '5h 40m' '4h 5m' '15h 55m' '7h 45m' '28h 20m' '4h 20m' '3h 40m'
 '8h 50m' '23h 45m' '24h 45m' '21h 35m' '8h 5m' '6h 25m' '15h 50m'
 '26h 25m' '24h 50m' '26h' '23h 5m' '7h 55m' '26h 20m' '23h 15m' '5h 20m'
 '4h' '9h 45m' '8h 20m' '17h 25m' '7h 5m' '34h 5m' '6h 5m' '5h 50m' '7h'
 '4h 25m' '13h 45m' '19h 15m' '22h 30m' '16h 25m' '13h 50m' '27h 5m'
 '28h 10m' '4h 40m' '15h 40m' '4h 35m' '18h 30m' '38h 15m' '6h 35m'
 '12h 30m' '11h 20m' '7h 35m' '29h 35m' '26h 55m' '23h 40m' '12h 50m'
 '9h 50m' '21h 55m' '10h 55m' '21h 10m' '20h 40m' '30h' '13h 10m' '8h 45m'
 '6h 10m' '17h 45m' '21h 45m' '3h 55m' '17h 20m' '30h 30m' '21h 25m'
 '12h 40m' '24h 35m' '19h 10m' '22h 40m' '14h 55m' '21h' '6h 45m'
 '28h 40m' '9h 40m' '16h 40m' '16h 20m' '16h 45m' '1h 15m' '6h 55m'
 '11h 25m' '14h 20m' '12h 5m' '24h 5m' '28h 15m' '17h 50m' '20h 20m'
 '28h 5m' '10h 20m' '14h 15m' '35h 15m' '35h 35m' '26h 40m' '28h'
 '14h 25m' '13h 5m' '37h 20m' '36h 10m' '25h 55m' '35h 5m' '19h 45m'
 '27h 55m' '47h' '10h 35m' '1h 35m' '16h 10m' '38h 20m' '6h' '16h 50m'
 '14h 10m' '23h 20m' '17h 40m' '11h 35m' '18h 20m' '6h 40m' '30h 55m'
 '24h 40m' '29h 50m' '28h 25m' '17h 15m' '22h 45m' '25h 25m' '21h 50m'
 '33h 15m' '30h 15m' '3h 35m' '27h 40m' '30h 25m' '18h 50m' '27h 45m'
 '15h 15m' '10h 40m' '26h 15m' '36h 25m' '26h 50m' '15h 45m' '19h 40m'
 '22h 25m' '19h 35m' '25h' '26h 45m' '38h' '4h 15m' '25h 10m' '18h 15m'
 '6h 50m' '23h 55m' '17h 55m' '23h 25m' '17h 10m' '24h 20m' '28h 30m'
 '27h 10m' '19h 20m' '15h 35m' '9h 25m' '21h 30m' '34h 25m' '18h 35m'
 '29h 40m' '26h 5m' '29h 5m' '27h 25m' '16h 30m' '11h 10m' '28h 55m'
 '29h 10m' '34h' '30h 40m' '30h 45m' '32h 55m' '10h 5m' '35h 20m' '32h 5m'
 '31h 40m' '19h 50m' '33h 45m' '30h 10m' '13h 40m' '19h 30m' '31h 30m'
 '34h 30m' '27h 50m' '38h 35m' '42h 5m' '4h 10m' '39h 5m' '3h 50m' '5m'
 '32h 30m' '31h 55m' '33h 20m' '27h 30m' '18h 55m' '9h 55m' '41h 20m'
 '20h 5m' '31h 50m' '42h 45m' '3h 25m' '37h 10m' '29h 30m' '32h 20m'
 '20h 50m' '40h 20m' '13h 35m' '47h 40m']

Total_Stops
['non-stop' '2 stops' '1 stop' '3 stops' '4 stops']

Additional_Info
['No info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' 'No Info' '1 Long layover' 'Change airports'
 'Business class' 'Red-eye flight' '2 Long layover']

In [13]:
df['Date_of_Journey']=pd.to_datetime(df['Date_of_Journey'])

In [14]:
df['Date']=df['Date_of_Journey'].dt.day
df['Month']=df['Date_of_Journey'].dt.month
df['Year']=df['Date_of_Journey'].dt.year
df.drop('Date_of_Journey',axis=1,inplace=True)
df.head(2)

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [15]:
df.drop('Route',axis=1,inplace=True)
df.head(2)

,Airline,Source,Destination,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019

In [16]:
df['Dep_Hour']=df['Dep_Time'].str.split(':').str[0].astype(int)
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1].astype(int)
df.drop('Dep_Time',axis=1,inplace=True)
df.head()

,Airline,Source,Destination,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50

In [17]:
df['Arrival_Time'].unique()

array(['01:10 22 Mar', '13:15', '04:25 10 Jun', ..., '06:50 10 Mar',
       '00:05 19 Mar', '21:20 13 Mar'], shape=(1343,), dtype=object)

In [18]:
df['Arrival_Time']=df['Arrival_Time'].str.split(' ').str[0]
df.head()

,Airline,Source,Destination,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min
0,IndiGo,Banglore,New Delhi,01:10,2h 50m,non-stop,No info,3897,24,3,2019,22,20
1,Air India,Kolkata,Banglore,13:15,7h 25m,2 stops,No info,7662,1,5,2019,5,50
2,Jet Airways,Delhi,Cochin,04:25,19h,2 stops,No info,13882,9,6,2019,9,25
3,IndiGo,Kolkata,Banglore,23:30,5h 25m,1 stop,No info,6218,12,5,2019,18,5
4,IndiGo,Banglore,New Delhi,21:35,4h 45m,1 stop,No info,13302,1,3,2019,16,50

In [19]:
df['Arrival_Hour']=df['Arrival_Time'].str.split(':').str[0].astype(int)
df['Arrival_Minute']=df['Arrival_Time'].str.split(':').str[1].astype(int)
df.drop('Arrival_Time',axis=1,inplace=True)
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35

In [20]:
# df['Duration'].unique()

In [21]:
# df['Duration_Hour']=df['Duration'].str.split('h').str[0].astype(int)
# df['Duration_Hour']

In [22]:
df[df['Duration'] == '5m']

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Minute
6474,Air India,Mumbai,Hyderabad,5m,2 stops,No info,17327,6,3,2019,16,50,16,55

In [23]:
df.drop(6474,axis=0,inplace=True)
df[df['Duration'] == '5m']

Empty DataFrame
Columns: [Airline, Source, Destination, Duration, Total_Stops, Additional_Info, Price, Date, Month, Year, Dep_Hour, Dep_Min, Arrival_Hour, Arrival_Minute]
Index: []

In [24]:
df.head()

,Airline,Source,Destination,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,2h 50m,non-stop,No info,3897,24,3,2019,22,20,1,10
1,Air India,Kolkata,Banglore,7h 25m,2 stops,No info,7662,1,5,2019,5,50,13,15
2,Jet Airways,Delhi,Cochin,19h,2 stops,No info,13882,9,6,2019,9,25,4,25
3,IndiGo,Kolkata,Banglore,5h 25m,1 stop,No info,6218,12,5,2019,18,5,23,30
4,IndiGo,Banglore,New Delhi,4h 45m,1 stop,No info,13302,1,3,2019,16,50,21,35

In [25]:
df['Duration_Hour']=df['Duration'].str.split('h').str[0].astype(int)
df['Duration_Minute']=df['Duration'].str.split(' ').str[1].str.split('m').str[0]
df['Duration_Minute'].fillna(0,axis=0,inplace=True)
df['Duration_Minute']=df['Duration_Minute'].astype(int)
df.drop('Duration',axis=1,inplace=True)
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,non-stop,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2 stops,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2 stops,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1 stop,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1 stop,No info,13302,1,3,2019,16,50,21,35,4,45

In [26]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [27]:
df['Total_Stops']=df['Total_Stops'].map(
    {
       'non-stop':0,
        '2 stops':2,
        '1 stop':1,
        '3 stops':3,
        '4 stops':4
    }
)
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2,No info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1,No info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1,No info,13302,1,3,2019,16,50,21,35,4,45

In [28]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [29]:
df['Additional_Info']=df['Additional_Info'].str.replace("No info","No Info")

In [30]:
df['Additional_Info'].unique()

array(['No Info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [31]:
for i in df.columns:
    if (df[i].dtype=='O'):
        print(i)
        print(df[i].unique())
        print()

Airline
['IndiGo' 'Air India' 'Jet Airways' 'SpiceJet' 'Multiple carriers' 'GoAir'
 'Vistara' 'Air Asia' 'Vistara Premium economy' 'Jet Airways Business'
 'Multiple carriers Premium economy' 'Trujet']

Source
['Banglore' 'Kolkata' 'Delhi' 'Chennai' 'Mumbai']

Destination
['New Delhi' 'Banglore' 'Cochin' 'Kolkata' 'Delhi' 'Hyderabad']

Additional_Info
['No Info' 'In-flight meal not included' 'No check-in baggage included'
 '1 Short layover' '1 Long layover' 'Change airports' 'Business class'
 'Red-eye flight' '2 Long layover']

In [32]:
df['Additional_Info'].value_counts()

Additional_Info
No Info                         8346
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [33]:
other_cols=['1 Long layover',
'Change airports',
'Business class',
'1 Short layover',
'Red-eye flight',
'2 Long layover']

for i in other_cols:
    df['Additional_Info']=df['Additional_Info'].str.replace(i,'Other')

In [34]:
df['Additional_Info'].value_counts()

Additional_Info
No Info                         8346
In-flight meal not included     1982
No check-in baggage included     320
Other                             33
Name: count, dtype: int64

In [35]:
X=df.drop('Price',axis=1)
y=df['Price']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [36]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
scaler=StandardScaler()
ohe=OneHotEncoder()

scal_features=[i for i in X_train.columns if X_train[i].dtype!='O']
ohe_features=[i for i in X_train.columns if X_train[i].dtype=='O']

ct=ColumnTransformer(
    [
        ('Standard Scaler',scaler,scal_features),
        ('One Hot Encoder',ohe,ohe_features)
    ]
)
X_train=ct.fit_transform(X_train)
X_test=ct.transform(X_test)

In [37]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor,AdaBoostRegressor
import xgboost


models={
    "Linear Regression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "SVM":SVR(),
    "KNeighborsRegressor":KNeighborsRegressor(),
    "DecisionTreeRegressor":DecisionTreeRegressor(),
    "RandomForestRegressor":RandomForestRegressor(),
    "GradientBoostingRegressor":GradientBoostingRegressor(),
    "AdaBoostRegressor":AdaBoostRegressor(),
    "Xgboost":xgboost.XGBRegressor()
}

In [38]:
from sklearn.metrics import r2_score

for i in range(len(list(models))):
    model_name=list(models)[i]
    model=list(models.values())[i]
        
    model.fit(X_train,y_train)
    y_pred=model.predict(X_test)

    print(f"{model_name}\nR^2 Score: {r2_score(y_test,y_pred)}\n")

Linear Regression
R^2 Score: 0.7142298926258721

Ridge
R^2 Score: 0.7135451667126972

Lasso
R^2 Score: 0.7142283412514184

SVM
R^2 Score: 0.04698336257953317

KNeighborsRegressor
R^2 Score: 0.8205437850163202

DecisionTreeRegressor
R^2 Score: 0.8281271361212125

RandomForestRegressor
R^2 Score: 0.89600874457313

GradientBoostingRegressor
R^2 Score: 0.8482469350275778

AdaBoostRegressor
R^2 Score: 0.19058398539922405

Xgboost
R^2 Score: 0.926456868648529

In [39]:
params={
    'booster':['gbtree','gblinear','dart'],
    'device':['cpu','cuda','gpu'],
    'nthread':[10,20,50,100,150,200],
    'tree_method':['auto', 'exact', 'approx', 'hist'] 
}

In [40]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=xgboost.XGBRegressor(),param_grid=params,cv=2,verbose=3)
grid.fit(X_train,y_train)
y_pred=grid.best_estimator_.predict(X_test)
print(r2_score(y_test,y_pred))

Fitting 2 folds for each of 216 candidates, totalling 432 fits
[CV 1/2] END booster=gbtree, device=cpu, nthread=10, tree_method=auto;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=10, tree_method=auto;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=10, tree_method=exact;, score=0.825 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=10, tree_method=exact;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=10, tree_method=approx;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=10, tree_method=approx;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=10, tree_method=hist;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=10, tree_method=hist;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=20, tree_method=auto;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=20, tree_method=auto;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=20, tree_method=exact;, score=0.825 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=20, tree_method=exact;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=20, tree_method=approx;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=20, tree_method=approx;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=20, tree_method=hist;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=20, tree_method=hist;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=50, tree_method=auto;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=50, tree_method=auto;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=50, tree_method=exact;, score=0.825 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=50, tree_method=exact;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=50, tree_method=approx;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=50, tree_method=approx;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=50, tree_method=hist;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=50, tree_method=hist;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=100, tree_method=auto;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=100, tree_method=auto;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=100, tree_method=exact;, score=0.825 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=100, tree_method=exact;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=100, tree_method=approx;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=100, tree_method=approx;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=100, tree_method=hist;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=100, tree_method=hist;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=150, tree_method=auto;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=150, tree_method=auto;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=150, tree_method=exact;, score=0.825 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=150, tree_method=exact;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=150, tree_method=approx;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=150, tree_method=approx;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=150, tree_method=hist;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=150, tree_method=hist;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=200, tree_method=auto;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=200, tree_method=auto;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=200, tree_method=exact;, score=0.825 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=200, tree_method=exact;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=200, tree_method=approx;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=200, tree_method=approx;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cpu, nthread=200, tree_method=hist;, score=0.826 total time=   0.0s
[CV 2/2] END booster=gbtree, device=cpu, nthread=200, tree_method=hist;, score=0.823 total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=10, tree_method=auto;, score=0.826 total time=   0.2s
[CV 2/2] END booster=gbtree, device=cuda, nthread=10, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=10, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=cuda, nthread=10, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=10, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=cuda, nthread=10, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=cuda, nthread=10, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=10, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=20, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=20, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=20, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=cuda, nthread=20, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=20, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=cuda, nthread=20, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=cuda, nthread=20, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=20, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=50, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=50, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=50, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=cuda, nthread=50, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=50, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=cuda, nthread=50, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=cuda, nthread=50, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=50, tree_method=hist;, score=0.823 total time=   0.2s
[CV 1/2] END booster=gbtree, device=cuda, nthread=100, tree_method=auto;, score=0.826 total time=   0.2s
[CV 2/2] END booster=gbtree, device=cuda, nthread=100, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=100, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=cuda, nthread=100, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=100, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=cuda, nthread=100, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=cuda, nthread=100, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=100, tree_method=hist;, score=0.823 total time=   0.2s
[CV 1/2] END booster=gbtree, device=cuda, nthread=150, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=150, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=150, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=cuda, nthread=150, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=150, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=cuda, nthread=150, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=cuda, nthread=150, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=150, tree_method=hist;, score=0.823 total time=   0.2s
[CV 1/2] END booster=gbtree, device=cuda, nthread=200, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=200, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=cuda, nthread=200, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=cuda, nthread=200, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=cuda, nthread=200, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=cuda, nthread=200, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=cuda, nthread=200, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=cuda, nthread=200, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=10, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=10, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=10, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=gpu, nthread=10, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=gpu, nthread=10, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=gpu, nthread=10, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=gpu, nthread=10, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=10, tree_method=hist;, score=0.823 total time=   0.2s
[CV 1/2] END booster=gbtree, device=gpu, nthread=20, tree_method=auto;, score=0.826 total time=   0.2s
[CV 2/2] END booster=gbtree, device=gpu, nthread=20, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=20, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=gpu, nthread=20, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=gpu, nthread=20, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=gpu, nthread=20, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=gpu, nthread=20, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=20, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=50, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=50, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=50, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=gpu, nthread=50, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=gpu, nthread=50, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=gpu, nthread=50, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=gpu, nthread=50, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=50, tree_method=hist;, score=0.823 total time=   0.2s
[CV 1/2] END booster=gbtree, device=gpu, nthread=100, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=100, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=100, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=gpu, nthread=100, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=gpu, nthread=100, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=gpu, nthread=100, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=gpu, nthread=100, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=100, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=150, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=150, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=150, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=gpu, nthread=150, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=gpu, nthread=150, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=gpu, nthread=150, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=gpu, nthread=150, tree_method=hist;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=150, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=200, tree_method=auto;, score=0.826 total time=   0.1s
[CV 2/2] END booster=gbtree, device=gpu, nthread=200, tree_method=auto;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gbtree, device=gpu, nthread=200, tree_method=exact;, score=nan total time=   0.0s
[CV 2/2] END booster=gbtree, device=gpu, nthread=200, tree_method=exact;, score=nan total time=   0.0s
[CV 1/2] END booster=gbtree, device=gpu, nthread=200, tree_method=approx;, score=0.826 total time=   0.4s
[CV 2/2] END booster=gbtree, device=gpu, nthread=200, tree_method=approx;, score=0.822 total time=   0.4s
[CV 1/2] END booster=gbtree, device=gpu, nthread=200, tree_method=hist;, score=0.826 total time=   0.2s
[CV 2/2] END booster=gbtree, device=gpu, nthread=200, tree_method=hist;, score=0.823 total time=   0.1s
[CV 1/2] END booster=gblinear, device=cpu, nthread=10, tree_method=auto;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=10, tree_method=auto;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=10, tree_method=exact;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=10, tree_method=exact;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=10, tree_method=approx;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=10, tree_method=approx;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=10, tree_method=hist;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=10, tree_method=hist;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=20, tree_method=auto;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=20, tree_method=auto;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=20, tree_method=exact;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=20, tree_method=exact;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=20, tree_method=approx;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=20, tree_method=approx;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=20, tree_method=hist;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=20, tree_method=hist;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=50, tree_method=auto;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=50, tree_method=auto;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=50, tree_method=exact;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=50, tree_method=exact;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=50, tree_method=approx;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=50, tree_method=approx;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=50, tree_method=hist;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=50, tree_method=hist;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=100, tree_method=auto;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=100, tree_method=auto;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=100, tree_method=exact;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=100, tree_method=exact;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=100, tree_method=approx;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=100, tree_method=approx;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=100, tree_method=hist;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=100, tree_method=hist;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=150, tree_method=auto;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=150, tree_method=auto;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=150, tree_method=exact;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=150, tree_method=exact;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=150, tree_method=approx;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=150, tree_method=approx;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=150, tree_method=hist;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=150, tree_method=hist;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=200, tree_method=auto;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=200, tree_method=auto;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=200, tree_method=exact;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=200, tree_method=exact;, score=0.644 total time=   0.0s
[CV 1/2] END booster=gblinear, device=cpu, nthread=200, tree_method=approx;, score=0.700 total time=   0.0s
[CV 2/2] END booster=gblinear, device=cpu, nthread=200, tree_method=approx;, score=0.644 total time=   0.0s

In [41]:
import pickle
pickle.dump(ct,open('../models/preprocessor.pkl','wb'))
pickle.dump(grid.best_estimator_,open('../models/model.pkl','wb'))

In [46]:
df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Dep_Hour,Dep_Min,Arrival_Hour,Arrival_Minute,Duration_Hour,Duration_Minute
0,IndiGo,Banglore,New Delhi,0,No Info,3897,24,3,2019,22,20,1,10,2,50
1,Air India,Kolkata,Banglore,2,No Info,7662,1,5,2019,5,50,13,15,7,25
2,Jet Airways,Delhi,Cochin,2,No Info,13882,9,6,2019,9,25,4,25,19,0
3,IndiGo,Kolkata,Banglore,1,No Info,6218,12,5,2019,18,5,23,30,5,25
4,IndiGo,Banglore,New Delhi,1,No Info,13302,1,3,2019,16,50,21,35,4,45

In [45]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
       'Price', 'Date', 'Month', 'Year', 'Dep_Hour', 'Dep_Min', 'Arrival_Hour',
       'Arrival_Minute', 'Duration_Hour', 'Duration_Minute'],
      dtype='object')